# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/Zac-HD/shed
    rev: 2023.6.1
    hooks:
    -   id: shed
        args: [--refactor, --py311-plus]
        types_or: [python, pyi, markdown, rst]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: check-ast
        language_version: python3
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: detect-private-key
    # -   id: pretty-format-json

# -   repo: https://github.com/bridgecrewio/checkov.git
#     rev: 3.1.46
#     hooks:
#     -   id: checkov_secrets
#     -   id: checkov
#         files: ./
